remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Rajat rai]
description: [B.Tech student with a strong interest in problem-solving, data analysis, and machine learning. Proficient in Java for DSA and Python for data analysis and ML, with hands-on experience through academic and self-driven projects.]
